# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: 
  - master

variables:
  buildConfiguration: 'Release'

stages: 
 - stage: StageOne
   jobs:
    - job: Windows
      pool:
        vmImage: 'windows-latest'
      steps:
      - script: echo hello from Windows

 - stage: StageTwo
   jobs:
     - job: "JobC"
       steps:
         - bash: echo "executing bash command"
 
 - stage: StageThree
   dependsOn: 
   - StageOne
   - StageTwo
   jobs:
    - job : JobD
      steps:    
        - bash: echo "executing bash command"