# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: 
  - master

variables:
  buildConfiguration: 'Release'

stages: 
 - stage: StageOne
   jobs:
    - job: 'JobA'
      timeoutInMinutes: 10
      pool:
       vmImage: ubuntu-latest
      steps: 
       - bash: echo "step executing bash command"
       - script: dotnet build --configuration $(buildConfiguration)
         displayName : 'dotnet build $(buildConfiguration)'

    - job: 'JobB'
      steps:
        - bash: echo "executing next job"
 - stage: StageTwo
   jobs:
     - job: "JobC"
       steps:
         - bash: echo "executing bash command"