name : GitHub Action Demo 
on: push
jobs:
 Example-actions-jobs:
  name: Exploring Github actions
  runs-on: ubuntu-latest
  steps:
   #Display the event that trigger the workflow
   - run: 'echo The job was trigger by ${{ github.event_name }}'

   #Runner information
   - run: echo This job is now running on a ${{ runner.os }} server hosted by github

   #Information about repository and branch
   - run: echo The name of branch is ${{ github.ref }} and repository ${{ github.repository }}

   #Checkout repository code
   - name: checkout repository code
   - uses: actions/checkout@v2

   - run: echo Repository ${{github.repository}} has been clone to runner
 
   - run: echo Repository- ${{github.repository}} has be copied to path- ${{ github.workspace }} on runner
   
   - name: list of files in repository 
     run:  ls ${{ github.workplace }}
       
   - run: Workflow now ready to test code

   
 
